# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.11.dev11+g435790b.d20230425"
__version_tuple__ = version_tuple = (0, 1, 11, "dev11", "g435790b.d20230425")
